projectgt/gtapp/urls.py
from django.urls import path
from .views import IndexView, ImagenView, GameView, RegistrationView, ProfileView
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'gtapp'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('imagen/', ImagenView.as_view(), name='imagen'),
    path('games/', GameView.as_view(), name='games'),
    path('login/', LoginView.as_view(template_name = 'login.html'), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(template_name = 'logout.html'), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

projectgt/projectgt/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gtapp/', include('gtapp.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.views.generic import RedirectView

urlpatterns += [
    path('', RedirectView.as_view(url='gtapp/', permanent=True)),
]

projectgt/gtapp/models.py
from django.db import models
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.password_validation import validate_password
from email_validator import validate_email, EmailNotValidError
from django.utils import timezone



class Imagen(models.Model):
    """Create Model Image"""

    name_imagen = models.CharField(max_length=50, help_text='Name description')
    image_location = models.ImageField(upload_to='', blank=True, null=True)
    text_imagen = models.TextField(max_length=10000)
    date_create_imagen = models.DateTimeField('Date Create Imagen')

    def __str__(self):
        return self.name_imagen

class Person(models.Model):
    """Create Model Person for profile"""

    first_name = models.CharField(max_length=50, help_text='Example Carlo Mario')
    last_name = models.CharField(max_length=50, help_text='Example Benedetti Postiga')
    nickname = models.CharField(unique=True, max_length=20, validators=[UnicodeUsernameValidator])
    cell_phone = models.IntegerField(help_text='3001112233')
    email_person = models.EmailField(unique=True) 
    date_create_user = models.DateTimeField(default=timezone.now)
    password_user = models.CharField(max_length=32, validators=[validate_password], 
                                    help_text='minimun eigth characters')

    REQUIRED_FIELDS = ["email_person"]       

    def email_validator(self):
        """Validate Email, with format correct """
        while True:
            try:
                self.email_person = validate_email(self.email_person).email_person
            except EmailNotValidError as e:
                print(str(e) + "Your Email should be in this format example@example.com")
    
    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name
    
    def __str__(self):
        return self.email_person

projectgt/gtapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email', 
        ]
        labels = {
            'username': 'Username',
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'email': 'Email', 
        }

projectgt/gtapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.models import User
from .models import Imagen, Person
from .forms import RegistrationForm



class IndexView(generic.ListView):
    template_name = 'index.html'
    model = Imagen

    def get_queryset(self):
        return Imagen.objects.all()


class ImagenView(generic.ListView):
    model = Imagen
    template_name = 'imagen.html'
    context_object_name= 'context_imagen'

    def get_queryset(self):
        return Imagen.objects.all()


class GameView(generic.ListView):
    template_name = 'games.html'
    context_object_name= 'ct_games'

    def palindromo(request):
        """Palindrome function"""
        if request.method == 'POST':
            palabra = request.POST.get('palabra', '')

            invertida = palabra[::-1]

            if invertida == palabra:
                return HttpResponse("Is Palindrome")
            else:
                return HttpResponse("Not is Palindrome")

        return render(request, 'games.html', palabra)

    def parorimpar(request):
        """Odd or even function"""

        if request.method == 'POST':
            num = request.POST.get('num', '')

            num = int(num)

            if num%2 == 0:
                return HttpResponse(num + "It's Even")
            else:
                return HttpResponse(num + "It's Odd") 
             
        return render(request, 'games.html', num)

    def get_queryset(self):
        return self.parorimpar, self.palindromo
    

class RegistrationView(generic.CreateView):
    model = User
    template_name = 'registration.html'
    context_object_name = 'context_registration'
    form_class = RegistrationForm

 
class ProfileView(generic.ListView):
    """View Profile User"""

    model = Person
    template_name = 'profile.html'
    

   

projectgt/gtapp/templates/base_games.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/games.css' %}">
    <title>GT APP</title>
</head>
<body>
    {% block content %}
      
    {% endblock content %}
</body>
</html>

projectgt/gtapp/templates/base_imagen.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/imagen.css' %}">
    <title>GT APP</title>
</head>
<body>
    {% block content %}
      
    {% endblock content %}
</body>
</html>

projectgt/gtapp/templates/base_index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>GT APP</title>
</head>
<body>
    {% block content %}
      
    {% endblock content %}
</body>
</html>

projectgt/gtapp/templates/base_login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'css/login.css' %}"> -->
    <title>GT APP</title>
</head>
<body>
    {% block content %}
      
    {% endblock content %} 
</body>
</html>

projectgt/gtapp/templates/base_profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <title>GT APP</title>
</head>
<body>
    {% block contenido %}
      
    {% endblock contenido %} 
</body>
</html>

projectgt/gtapp/templates/base_register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'css/register.css' %}"> -->
    <title>GT APP</title>
</head>
<body>
    {% block content %}
      
    {% endblock content %}
</body>
</html>

projectgt/gtapp/templates/games.html
{% extends "base_games.html" %}
{% load static %}

{% block content %}
    {% csrf_token %}
    <div class="conteiner">
        {% if ct_games %}
            <form action="" method="post" style="text-align: center" enctype="multipart/form-data">{% csrf_token %}
                <div class="content">
                    <h1>Odd or Even</h1>
                    <p>It allows us to know if the number entered is even or odd.</p>
                    <input type="text" id="{{ parorimpar.num }}" class="form-control" name="{{ parorimpar.num }}" placeholder="Number">
                    <button type="submit" class="btn">Check</button>
                </div>
            </form>
        
            <form action="" method="post" style="text-align: center" enctype="multipart/form-data">{% csrf_token %}
                <div class="content">
                    <h1>Palindrome</h1>
                    <p>It allows us to know if a word is written the same way forward as backwards</p>
                    <input type="text" id="palabra" class="form-control" name="palabra" placeholder="Word">
                    <button type="submit" class="btn btn-success">Check</button>
                </div>
            </form>
        {% endif %}
    </div>
    <br> <br> <br>
    <hr>
    <a id="back" href="{% url 'gtapp:index' %}">Back to page main?</a>
{% endblock content %}

projectgt/gtapp/templates/imagen.html
{% extends "base_imagen.html" %}
{% load static %}

{% block content %}
    <div class="flex-container" enctype="multipart/form-data">
        {% csrf_token %}
        {% if context_imagen %}
        {% for Imagen in context_imagen %}
            <div class="col">
                <div class="col-md-8">
                    <img src="{{ Imagen.image_location.url }}" alt="{{ Imagen.name_imagen }}" 
                    BORDER="3">   
                </div>           
                <div class="card" style="width: 25rem;" data-layer="0">
                    <h5 class="card-title">{{ Imagen.name_imagen }}</h5>
                    <p class="card-text">{{ Imagen.text_imagen }}.</p>
                </div>  
            </div>
        {% endfor %}
        {% else %}
            <br> <br> <br>
            <p>No Imagen are available</p>
        {% endif %}
    </div>
    <br> <br> <br>
    <hr>
    <a id="back" href="{% url 'gtapp:index' %}">Back to page main?</a>
{% endblock content %}

projectgt/gtapp/templates/index.html
{% extends "base_index.html" %}
{% load static %}

{% block content %}
    <header>
        <div class="main">
            <nav class="navbar navbar-inverse" role="navigation" style="margin-bottom: 6">
                <ul>
                    <li class="active"><a href="{% url 'gtapp:index' %}">HOME</a></li>
                    <li><a href="{% url 'gtapp:imagen' %}">Imagens</a></li>
                    <li><a href="">Videos</a></li>
                    <li><a href="">Music</a></li>
                    <li><a href="{% url 'gtapp:games' %}">MiniGames</a></li>
                    <li><a href="">Posts</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'gtapp:profile' %}">Profile</a></li>
                        <li><a class="logout1" href="{% url 'gtapp:logout' %}">Log Out</a></li>
                    {% else %}
                        <li><a class="login1" href="{% url 'gtapp:login' %}">Log In</a></li>
                    {% endif %} 
                </ul>
            </nav>
        </div>
    </header>
    <div class="row" style="padding:30px;margin-top:30px;"> 
        {% csrf_token %}
        {% if user.is_authenticated %}
        <h1>&#10055; Welcome to GT APP {{ user.first_name }} {{ user.last_name }} &#10055;</h1>
        {% else %}
        <h1>&#10055; Welcome to GT APP &#10055;</h1>
    {% endif %} 
        <div class="container-img">
            <picture>        
                <img src="{% static 'images/paisaje1.jpg' %}" alt="Paisaje">     
            </picture>
        </div>
    </div>
{% endblock content %}

projectgt/gtapp/templates/login.html
{% extends "base_login.html" %}
{% load static %}

{% block content %}
    <form class="form" method="POST">{% csrf_token %}
        <table>
            {{ form.as_p }}
        </table>
        <button type="submit" id="buttonlogin">Sign In</button>
    </form> 
    <br>  <br>
    <center>
        <a href="{% url 'gtapp:registration' %}">Sign In</a>
    </center>
    <br> <br>
    <a href="{% url 'gtapp:index' %}">Back to Again?</a>
{% endblock content %} 

projectgt/gtapp/templates/logout.html
{% extends "base_login.html" %}
{% load static %}

{% block content %}
    <h2>You closed Section, come back soon</h2>
    <br> <br>
    <a href="{% url 'gtapp:index' %}">Back to Again?</a>
{% endblock content %} 

projectgt/gtapp/templates/profile.html
{% extends "base_profile.html" %}

{% block contenido  %}
    <div id="main-profile">
        <nav class="navbar navbar-inverse" role="navigation" style="margin-bottom: 6">
            <ul>
                <li><a class="active" href="{% url 'gtapp:index' %}">Home</a></li>
                <li><a class="pestaña" href="#profile">User Data</a></li>
                <li><a class="pestaña" href="#messages">Posted Messages</a></li> 
                <li><a class="pestaña" href="#videos">Published Videos</a></li>
                <li><a class="logout" href="{% url 'gtapp:logout' %}">Log Out</a></li>
            </ul>
        </nav>    
    </div>
        
    <!-- <div id="profile" class="box">
        <li><p>User Firts Name: {{ user.first_name }}</p></li>
        <br> 
        <li><p>User Last Name: {{ user.last_name }}</p></li>
        <br>            
        <li><p>User Email: {{ user.email }}</p></li>
    </div>
    <div id="messages" class="box"> 
        <h3>Message Title</h3>
        <p>
            Los mensajes de texto, o SMS (servicio de mensajes cortos) son un método de comunicación que 
            envía mensajes entre teléfonos móviles (SMS o SMPP) o desde un PC o un dispositivo portátil 
            a un teléfono móvil (SMTP). La parte «corta» proviene del tamaño máximo de un mensaje de texto, 
            que es de 160 caracteres (letras, números o símbolos del alfabeto latino) independientemente del 
            teléfono, el proveedor o la tecnología.
        </p>
    </div>
    <div id="videos" class="box">
        <h3>Video Title </h3>
        <p>El video digital (en España, vídeo digital) es una representación de imágenes en movimiento en 
            la forma de datos digitales codificados, a diferencia del video analógico que representa estas 
            imágenes mediante señales analógicas.
        </p>
    </div> -->
{% endblock contenido  %}

projectgt/gtapp/templates/registration.html
{% extends "base_register.html" %}
{% load static %}

{% block content %}
    <form action="{% url 'gtapp:index' %}" method="POST">{% csrf_token %}
        <table>
            {{ form.as_p }}
        </table>
        <button type="submit">Sign In</button>
    </form> 
    <br> <br>
    <a href="{% url 'gtapp:index' %}">Back to Again?</a>
{% endblock content %} 